### ISSUE TITLE
Study the HIG

### ISSUE THREAD

**Issue by yutzhead** [d4nj1/TLPUI#1]
https://developer.gnome.org/hig/stable/

Just sayin'.

**Comment by d4nj1** [comment]
Yes, I should really do this. There is much space for improving this. ;) I had my focus on functionality first.
If you have any concrete visual ideas please let me know.

**Comment by d4nj1** [comment]
Please check the last version. I added some HIG related changes.

**Comment by d4nj1** [comment]
No more requests. I would say fixed.
