### ISSUE TITLE
Quit button w/ discard

### ISSUE THREAD

**Issue by linrunner** [d4nj1/TLPUI#10]
Implement a button "Quit" which discards changes (after user confirmation).

**Comment by d4nj1** [comment]
Behavior should be as expected.

**Comment by linrunner** [comment]
Discard dialog must not appear when there is no change actually.

**Comment by d4nj1** [comment]
Fixed, see
https://github.com/d4nj1/TLPUI/commit/afef79fe798d79c285d8713c133db29fd1ba8117
and
https://github.com/d4nj1/TLPUI/commit/c34a78d4214c9b3b2989ba0601dc5032c3970845

**Comment by d4nj1** [comment]
* Dialog shows changed items now.
* Will be beautified in the near future

**Comment by linrunner** [comment]
Works.

I'd prefer to mark the changes in the original input dialog by some color rather than listing them in the confirmation dialog. Looks a bit cluttered.

**Comment by d4nj1** [comment]
I think the last comment refers to #16 and will be implemented as a part of that feature.
