### ISSUE TITLE
Error while opening tlpui

### ISSUE THREAD

**Issue by throwaway69420-69420** [d4nj1/TLPUI#100]
Running tlpui gives me this output 
`
Traceback (most recent call last):
  File "/usr/bin/tlpui", line 33, in <module>
    sys.exit(load_entry_point('TLPUI==1.4.0', 'gui_scripts', 'tlpui')())
  File "/usr/lib/python3.9/site-packages/tlpui/__main__.py", line 38, in main
    window.add(create_main_box(window))
  File "/usr/lib/python3.9/site-packages/tlpui/mainui.py", line 311, in create_main_box
    configbox = create_config_box(window)
  File "/usr/lib/python3.9/site-packages/tlpui/configui.py", line 27, in create_config_box
    tlp_categories = get_tlp_categories(window)
  File "/usr/lib/python3.9/site-packages/tlpui/configui.py", line 238, in get_tlp_categories
    configbox = create_item_box(configobjects, language.CDT_(transdescription), grouptitle, window)
  File "/usr/lib/python3.9/site-packages/tlpui/configui.py", line 165, in create_item_box
    configwidget = create_config_widget(configname, configobject.datatype, configobject.values, window)
  File "/usr/lib/python3.9/site-packages/tlpui/configui.py", line 81, in create_config_widget
    configwidget = gtkselection.create_selection_box(configname, objectvalues)
  File "/usr/lib/python3.9/site-packages/tlpui/ui_config_objects/gtkselection.py", line 14, in create_selection_box
    settings.tlpconfig[configname].stateimage.warn_unknown_config_value(configvalue)
AttributeError: 'NoneType' object has no attribute 'warn_unknown_config_value'
`

output of tlp-stat -c is
`
--- TLP 1.4.0 --------------------------------------------

+++ Configured Settings:
/etc/tlp.conf L0027: TLP_ENABLE="1"
defaults.conf L0005: TLP_WARN_LEVEL="3"
/etc/tlp.conf L0041: TLP_PERSISTENT_DEFAULT="0"
defaults.conf L0007: DISK_IDLE_SECS_ON_AC="0"
defaults.conf L0008: DISK_IDLE_SECS_ON_BAT="2"
defaults.conf L0009: MAX_LOST_WORK_SECS_ON_AC="15"
defaults.conf L0010: MAX_LOST_WORK_SECS_ON_BAT="60"
/etc/tlp.conf L0113: CPU_ENERGY_PERF_POLICY_ON_AC="balance_performance"
/etc/tlp.conf L0114: CPU_ENERGY_PERF_POLICY_ON_BAT="power"
/etc/tlp.conf L0144: SCHED_POWERSAVE_ON_AC="0"
/etc/tlp.conf L0145: SCHED_POWERSAVE_ON_BAT="1"
/etc/tlp.conf L0152: NMI_WATCHDOG="0"
/etc/tlp.conf L0168: DISK_DEVICES="nvme0n1 sda"
/etc/tlp.conf L0177: DISK_APM_LEVEL_ON_AC="254 254"
/etc/tlp.conf L0178: DISK_APM_LEVEL_ON_BAT="128 128"
defaults.conf L0019: DISK_APM_CLASS_DENYLIST="usb ieee1394"
defaults.conf L0020: DISK_IOSCHED="keep keep"
/etc/tlp.conf L0218: SATA_LINKPWR_ON_AC="med_power_with_dipm max_performance"
/etc/tlp.conf L0219: SATA_LINKPWR_ON_BAT="med_power_with_dipm min_power"
defaults.conf L0023: AHCI_RUNTIME_PM_ON_AC="on"
defaults.conf L0024: AHCI_RUNTIME_PM_ON_BAT="auto"
/etc/tlp.conf L0240: AHCI_RUNTIME_PM_TIMEOUT="15"
defaults.conf L0026: PCIE_ASPM_ON_AC="default"
defaults.conf L0027: PCIE_ASPM_ON_BAT="default"
/etc/tlp.conf L0283: RADEON_DPM_PERF_LEVEL_ON_AC="auto"
/etc/tlp.conf L0284: RADEON_DPM_PERF_LEVEL_ON_BAT="auto"
/etc/tlp.conf L0268: RADEON_POWER_PROFILE_ON_AC="mid"
/etc/tlp.conf L0269: RADEON_POWER_PROFILE_ON_BAT="mid"
/etc/tlp.conf L0290: WIFI_PWR_ON_AC="off"
/etc/tlp.conf L0291: WIFI_PWR_ON_BAT="off"
/etc/tlp.conf L0297: WOL_DISABLE="Y"
/etc/tlp.conf L0304: SOUND_POWER_SAVE_ON_AC="0"
/etc/tlp.conf L0305: SOUND_POWER_SAVE_ON_BAT="1"
/etc/tlp.conf L0312: SOUND_POWER_SAVE_CONTROLLER="Y"
/etc/tlp.conf L0321: BAY_POWEROFF_ON_AC="0"
/etc/tlp.conf L0322: BAY_POWEROFF_ON_BAT="0"
/etc/tlp.conf L0328: BAY_DEVICE="sr0"
/etc/tlp.conf L0334: RUNTIME_PM_ON_AC="on"
/etc/tlp.conf L0335: RUNTIME_PM_ON_BAT="auto"
/etc/tlp.conf L0352: RUNTIME_PM_DRIVER_DENYLIST="nouveau nvidia"
/etc/tlp.conf L0358: USB_AUTOSUSPEND="1"
defaults.conf L0045: USB_EXCLUDE_AUDIO="1"
/etc/tlp.conf L0373: USB_EXCLUDE_BTUSB="1"
/etc/tlp.conf L0380: USB_EXCLUDE_PHONE="1"
/etc/tlp.conf L0387: USB_EXCLUDE_PRINTER="1"
/etc/tlp.conf L0394: USB_EXCLUDE_WWAN="1"
/etc/tlp.conf L0407: USB_AUTOSUSPEND_DISABLE_ON_SHUTDOWN="1"
/etc/tlp.conf L0416: RESTORE_DEVICE_STATE_ON_STARTUP="0"
defaults.conf L0052: RESTORE_THRESHOLDS_ON_BAT="0"
defaults.conf L0053: NATACPI_ENABLE="1"
defaults.conf L0054: TPACPI_ENABLE="1"
defaults.conf L0055: TPSMAPI_ENABLE="1"
/etc/tlp.conf L0034: TLP_DEFAULT_MODE="BAT"
/etc/tlp.conf L0080: CPU_SCALING_GOVERNOR_ON_AC=""
/etc/tlp.conf L0081: CPU_SCALING_GOVERNOR_ON_BAT="powersave"
/etc/tlp.conf L0089: CPU_SCALING_MIN_FREQ_ON_AC="0"
/etc/tlp.conf L0090: CPU_SCALING_MAX_FREQ_ON_AC="1800000"
/etc/tlp.conf L0091: CPU_SCALING_MIN_FREQ_ON_BAT="0"
/etc/tlp.conf L0092: CPU_SCALING_MAX_FREQ_ON_BAT="1100000"
/etc/tlp.conf L0109: ENERGY_PERF_POLICY_ON_AC="balance-performance"
/etc/tlp.conf L0110: ENERGY_PERF_POLICY_ON_BAT="power"
/etc/tlp.conf L0123: CPU_MIN_PERF_ON_AC="0"
/etc/tlp.conf L0124: CPU_MAX_PERF_ON_AC="100"
/etc/tlp.conf L0125: CPU_MIN_PERF_ON_BAT="0"
/etc/tlp.conf L0126: CPU_MAX_PERF_ON_BAT="33"
/etc/tlp.conf L0136: CPU_BOOST_ON_AC="1"
/etc/tlp.conf L0137: CPU_BOOST_ON_BAT="0"
/etc/tlp.conf L0256: INTEL_GPU_MIN_FREQ_ON_AC="300"
/etc/tlp.conf L0257: INTEL_GPU_MIN_FREQ_ON_BAT="300"
/etc/tlp.conf L0258: INTEL_GPU_MAX_FREQ_ON_AC="900"
/etc/tlp.conf L0259: INTEL_GPU_MAX_FREQ_ON_BAT="600"
/etc/tlp.conf L0260: INTEL_GPU_BOOST_FREQ_ON_AC="900"
/etc/tlp.conf L0261: INTEL_GPU_BOOST_FREQ_ON_BAT="800"
/etc/tlp.conf L0275: RADEON_DPM_STATE_ON_AC="performance"
/etc/tlp.conf L0276: RADEON_DPM_STATE_ON_BAT="battery"
/etc/tlp.conf L0342: RUNTIME_PM_DENYLIST="bb:dd.f 11:22.3 44:55.6 02:00.0"
/etc/tlp.conf L0366: USB_DENYLIST="0bda:0411 0bda:8153"
/etc/tlp.conf L0423: DEVICES_TO_DISABLE_ON_STARTUP=""
/etc/tlp.conf L0458: DEVICES_TO_DISABLE_ON_BAT_NOT_IN_USE="bluetooth"
/etc/tlp.conf L0500: DEVICES_TO_DISABLE_ON_LAN_CONNECT=""
/etc/tlp.conf L0508: DEVICES_TO_ENABLE_ON_LAN_DISCONNECT=""
`

**Comment by throwaway69420-69420** [comment]
it got fixed when I copy pasted a new config into /etc/tlp.conf

**Comment by throwaway69420-69420** [comment]
it got fixed when I copy pasted the new config into /etc/tlp.conf

**Comment by d4nj1** [comment]
Hi @throwaway69420-69420 ,
it was a bug in the UI anyway. A state image was referenced before being initialized. Should be fixed in https://github.com/d4nj1/TLPUI/releases/tag/tlpui-1.4.0-1 .

Thanks for reporting.

**Comment by throwaway69420-69420** [comment]
thanks :)
