### ISSUE TITLE
Can't launch tlpui, what did i do wrong?

### ISSUE THREAD

**Issue by Lolis4TheWin** [d4nj1/TLPUI#103]
Error:
`(tlpui:706151): Gtk-WARNING **: 20:26:02.558: Theme parsing error: gtk.css:3:12: Not using units is deprecated. Assuming 'px'.
Traceback (most recent call last):
  File "/usr/bin/tlpui", line 33, in <module>
    sys.exit(load_entry_point('TLPUI==1.4.0.post1', 'gui_scripts', 'tlpui')())
  File "/usr/lib/python3.10/site-packages/tlpui/__main__.py", line 31, in main
    init_tlp_file_config()
  File "/usr/lib/python3.10/site-packages/tlpui/file.py", line 41, in init_tlp_file_config
    settings.tlpconfig_defaults = get_tlp_config_defaults(tlpversion)
  File "/usr/lib/python3.10/site-packages/tlpui/file.py", line 27, in get_tlp_config_defaults
    tlpconfig_defaults = extract_default_tlp_configs(f"{settings.workdir}/defaults/tlp-{tlpversion}.conf")
  File "/usr/lib/python3.10/site-packages/tlpui/filehelper.py", line 41, in extract_default_tlp_configs
    fileopener = open(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3.10/site-packages/tlpui/defaults/tlp-1_5.conf'`

**Comment by d4nj1** [comment]
Hi,
the problem is that your TLP-UI version is not the latest (TLPUI==1.4.0.post1). What Linux distro are you running? How did you install TLP-UI? If you installed via your package manager it might be that the package has not been upgraded yet.
The latest master version is already upgraded to be compatible with TLP 1.5.

**Comment by Lolis4TheWin** [comment]
I'm currently running manjaro xfce, i installed tlpui via gui pacman (probably community build). 
It says the version date 2021.12.13 and if i look into the build files i see this:
![image](https://user-images.githubusercontent.com/50179148/149831738-f7730c3e-bede-440a-a169-9437554e76d6.png)

**Comment by Lolis4TheWin** [comment]
Okay, sorry, to bother you, i reinstalled it from the AUR and it launches. 
Thanks for your time and sorry for bothering you.

**Comment by d4nj1** [comment]
No worries. Thanks for feedback.
