### ISSUE TITLE
Error in install

### ISSUE THREAD

**Issue by Applied-Energetic** [d4nj1/TLPUI#106]
ubuntu 20.04
Cpu AMD
I install the prerequisites
then python3, but have a error
---
17:46:58 › python3 -m tlpui   
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/xiayue/software/tlpui/TLPUI/tlpui/__main__.py", line 4, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
---
then i try to  install denpncies
threre is another error
---
17:51:34 › pip install pycairo>=1.18.1 PyGObject>=3.34.0        

zsh: 1.18.1 not found
---
so I try  pip install pycairo      AND             pip install PyGObject                   

17:52:17 › pip install pycairo                           

/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pycairo in /usr/lib/python3/dist-packages (1.16.2)

17:52:53 › pip install PyGObject         
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: PyGObject in /usr/lib/python3/dist-packages (3.36.0)
Requirement already satisfied: pycairo>=1.11.1 in /usr/lib/python3/dist-packages (from PyGObject) (1.16.2)

But it dont work

**Comment by Applied-Energetic** [comment]
Do you have some advice?

**Comment by d4nj1** [comment]
Hi,
for Ubuntu 20.04 the current Python version is still 3.8.x
If you are using Python 3.9 you have to also install all dependencies in regards to Python 3.9. For using pip that would mean that you have to also install and use pip3.9.

Could you please execute `pip --version` and `pip3 --version` to see what is configured on your system?

If you can I would suggest you run tlpui with Python 3.8 until 3.9/3.10 is set to be the new standard version.

Kind regards

**Comment by d4nj1** [comment]
Please reopen when the issue still exists.
