### ISSUE TITLE
RPM build

### ISSUE THREAD

**Issue by LordTermor** [d4nj1/TLPUI#109]
In theory it's possible to build RPM using `setuptools` but because of [this](https://github.com/pypa/setuptools/issues/767) the package can't be packaged as it contains following files which has spaces in their file names:
`tlpui/icons/themeable/hicolor/scalable/actions/tlpui-ThinkPad Battery-symbolic.svg`
`tlpui/icons/themeable/hicolor/scalable/actions/tlpui-Radio Device Wizard-symbolic.svg`

Removing/renaming these files procudes proper RPM but of course the software misses those icons in this case.

Is there anything can be done in this regard?

**Comment by d4nj1** [comment]
Hi @LordTermor 
I fixed the filenames. Please retry to build the rpm. I'm happy to apply further changes if there are still blockers.

Cheers

**Comment by d4nj1** [comment]
Please reopen if you have still issues building the rpm.
