### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by linrunner** [d4nj1/TLPUI#11]
Implement translations for:
- Item title
- Item long description

**Comment by d4nj1** [comment]
* Translation file added for UI items
* Translation file added for config categories and descriptions

Question:
Do we really need a translation for item title? Is the tlp config name not clear enough?
I would prefer to not localize this to avoid user misunderstanding.

**Comment by d4nj1** [comment]
Group and title items are translateable. configschema.json does not contain any language specific data anymore. I think first language support implementation is finished.
