### ISSUE TITLE
Flatpak version not working

### ISSUE THREAD

**Issue by SimonePietrogiacomi** [d4nj1/TLPUI#110]
Flatpak version can't see tlp while `tlp-stat -s` says that it's enabled

OS: Linux Mint 20.3 (based on Ubuntu 20.04)
tlp version: 1.3.1 from apt
Error message: "tlp not found on system. Please install first."

**Comment by junocomp** [comment]
I am also having the same issue

**Comment by d4nj1** [comment]
On Ubuntu systems I also have to look into `/usr/sbin`. A fix should be on it's way. Please update to 1.5.0-5 once it's build and published on Flathub.

**Comment by d4nj1** [comment]
As there are no complains I guess it's fixed. :wink:

**Comment by Letronxis** [comment]
no, it still happen on the flatpak version of openSUSE Leap15.6. It told me not install lspci. However, lspci , tlp in /usr/sbin
