### ISSUE TITLE
tlp not fount on your system. please install first 

### ISSUE THREAD

**Issue by Ahmed00010** [d4nj1/TLPUI#116]
I get the above when I open tlpui , I'm sure that tlp is installed 

`ahmed@ahmed-pc:~$ tlp-stat -s
--- TLP 1.5.0 --------------------------------------------

+++ System Info
System         = LENOVO Lenovo ideapad 100-15IBD 80QQ
BIOS           = E0CN60WW
OS Release     = Debian GNU/Linux bookworm/sid
Kernel         = 6.0.0-6-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.12-1 (2022-12-09) x86_64
/proc/cmdline  = BOOT_IMAGE=/boot/vmlinuz-6.0.0-6-amd64 root=UUID=### ro quiet splash
Init system    = systemd v252 (252.4-1)
Boot mode      = UEFI

+++ TLP Status
State          = enabled
RDW state      = enabled
Last run       = 12:05:22 PM,    179 sec(s) ago
Mode           = battery
Power source   = battery`

my system
Operating System: Debian GNU/Linux
KDE Plasma Version: 5.26.4
KDE Frameworks Version: 5.101.0
Qt Version: 5.15.7
Kernel Version: 6.0.0-6-amd64 (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i3-5005U CPU @ 2.00GHz
Memory: 3.8 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 5500
Manufacturer: LENOVO
Product Name: 80QQ
System Version: Lenovo ideapad 100-15IBD

------EDIT-------
I fixed the issue by removing the native version and installing the flatpak

**Comment by markd89** [comment]
I get the same error, sudo tlpui does work. 

Does tlpui need to run as root?

**Comment by D3rpi** [comment]
I have a similar issue but I am using the python script and running python3 -m tlpui.
I have confirmed that tlp is indeed running on the machine by running tlp-stat -s

**Comment by d4nj1** [comment]
Hi,
it seems that the **tlp** and **tlp-stat** executables are not in the expected locations for bookworm. It might be that they are located in **/usr/sbin** or somewhere not accessible by tlpui. Can you please share the output of:

`which tlp`

and

`which tlp-stat`

Thanks in advance

**Comment by markd89** [comment]
which tlp-stat returns /usr/bin/tlp-stat

which tlp does not find anything

I searched and do find tlp in /usr/sbin/ which is a directory not in PATH

**Comment by d4nj1** [comment]
Hi,
I updated the check scripts to also look into **/usr/sbin** when not found with **which**.
This probably affects mostly bookworm and distros that put **tlp** in **/usr/sbin**.

Please try out latest master or https://github.com/d4nj1/TLPUI/tree/tlpui-1.5.0-6 and report back.

**Comment by d4nj1** [comment]
As this is reported fixed in #117 I close the issue.
