### ISSUE TITLE
Description markup

### ISSUE THREAD

**Issue by linrunner** [d4nj1/TLPUI#12]
Implement markup support for long descriptions: bold/italic chars, lists, ...

**Comment by d4nj1** [comment]
Long descriptions are using object Gtk.Label():
http://python-gtk-3-tutorial.readthedocs.io/en/latest/label.html

So Pango markup format is supported OOTB:
https://developer.gnome.org/pango/stable/PangoMarkupFormat.html#PangoMarkupFormat

Is this enough?

**Comment by d4nj1** [comment]
Description is now in language po-files and can be extended with Pango markup.
