### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by Hellzevir** [d4nj1/TLPUI#120]
Hello,

I have been using TLP since 2015, and discovered two years ago tlp-ui. I have just reinstalled it on my new system and I can see that for this great tool, that makes the use of tlp easier, French translation is still missing.

I would like to contribute and would be pleased to provide with a translation.

Thanks for your interest.

**Comment by d4nj1** [comment]
Thanks for your offerings. I just created #121 which will ease up the process once implemented.

**Comment by Hellzevir** [comment]
Ok, thanks. So, like you suggested to my Italian pal, I'm going to start translating PO files into French.

**Comment by d4nj1** [comment]
Awesome! Thanks for the efforts.

**Comment by Hellzevir** [comment]
Translation is finished! (based on 1.5.0-5). I'm just checking and correcting my work.
Once finished, should I upload the .mo and .po files in TLPUI/tlpui/lang/, or should I attach them here?
Thanks.

**Comment by d4nj1** [comment]
Hi,
ideally I would suggest you create **/tlpui/lang/fr_FR/LC_MESSAGES** folder with your translated .po files in it and then create a PR for it.
I would then generate the .mo files and add the necessary language related stuff so that you can select French in the UI.

Would that ok for you?

**Comment by Hellzevir** [comment]
Hi, perfect! I'll upload my .po files as you propose, and then I'll leave the rest to you. ;-)

**Comment by Hellzevir** [comment]
Hi! Done. Hope everything is fine.

**Comment by d4nj1** [comment]
Hi,
I finally added French translation. This will be released once I finish adopting TLPUI to TLP 1.6.

Thanks and kind regards
