### ISSUE TITLE
Flatpak: Gnome 42 runtime EOL

### ISSUE THREAD

**Issue by pjolt** [d4nj1/TLPUI#125]
During update today 

`Info: runtime org.gnome.Platform branch 42 is end-of-life, with reason:
   The GNOME 42 runtime is no longer supported as of March 21, 2023. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   com.github.d4nj1.tlpui`

**Comment by d4nj1** [comment]
Thanks for the hint.
I'm still waiting for the Flathub build server to publish the new release.  This had also been reported in #124.
Maybe I shouldn't have closed that issue so early.

**Comment by pjolt** [comment]
Oh, thanks for the quick response and the app! Much appreciated! 
I'll be honest, It did not cross my mind to check already closed issues.

**Comment by d4nj1** [comment]
It has just been uploaded as we spoke. ;)
