### ISSUE TITLE
ERROR: One or more files did not pass the validity check!

### ISSUE THREAD

**Issue by Nambers** [d4nj1/TLPUI#137]
Hi, this is what I got from my Arch `yay -Syyu`
```
[sudo] password for [HOME]: 
:: Synchronizing package databases...
 core                                                             128.1 KiB   104 KiB/s 00:01 [#######################################################] 100%
 extra                                                              8.3 MiB  4.44 MiB/s 00:02 [#######################################################] 100%
 multilib                                                         143.0 KiB   694 KiB/s 00:00 [#######################################################] 100%
:: Searching AUR for updates...
:: Searching databases for updates...
 -> Flagged Out Of Date AUR Packages: burpsuite  chromeos-kde-git  tlpui
:: 1 package to upgrade/install.
1  aur/tlpui  1:1.5.0.7-1 -> 1:1.6.0-1
==> Packages to exclude: (eg: "1 2 3", "1-3", "^4" or repo name)
 -> Excluding packages may cause partial upgrades and break systems
==> 
AUR Explicit (1): tlpui-1:1.6.0-1
:: PKGBUILD up to date, skipping download: tlpui
  1 tlpui                                    (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> A
:: Deleting (1/1): /home/[HOME]/.cache/yay/tlpui
HEAD is now at 51f745f Auto-update to version 1.6.0
Removing src/
Removing tlpui-1.6.0.zip
  1 tlpui                                    (Installed) (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> N
==> Making package: tlpui 1:1.6.0-1 (Wed 06 Sep 2023 11:41:48 PM EDT)
==> Retrieving sources...
  -> Downloading tlpui-1.6.0.zip...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  619k    0  619k    0     0  1507k      0 --:--:-- --:--:-- --:--:-- 1507k
  -> Found tlpui.desktop
==> WARNING: Skipping verification of source file PGP signatures.
==> Validating source files with sha256sums...
    tlpui-1.6.0.zip ... FAILED
    tlpui.desktop ... Passed
==> ERROR: One or more files did not pass the validity check!
 -> error downloading sources: /home/[HOME]/.cache/yay/tlpui 
         context: exit status 1 
         

:: (1/1) Parsing SRCINFO: tlpui
==> Making package: tlpui 1:1.6.0-1 (Wed 06 Sep 2023 11:41:50 PM EDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found tlpui-1.6.0.zip
  -> Found tlpui.desktop
==> Validating source files with sha256sums...
    tlpui-1.6.0.zip ... FAILED
    tlpui.desktop ... Passed
==> ERROR: One or more files did not pass the validity check!
 -> error making: tlpui-exit status 1
 -> Failed to install the following packages. Manual intervention is required:
tlpui - exit status 1
```

**Comment by Elias0419** [comment]
> Hi, this is what I got from my Arch `yay -Syyu`
> 
> ```
> [sudo] password for [HOME]: 
> :: Synchronizing package databases...
>  core                                                             128.1 KiB   104 KiB/s 00:01 [#######################################################] 100%
>  extra                                                              8.3 MiB  4.44 MiB/s 00:02 [#######################################################] 100%
>  multilib                                                         143.0 KiB   694 KiB/s 00:00 [#######################################################] 100%
> :: Searching AUR for updates...
> :: Searching databases for updates...
>  -> Flagged Out Of Date AUR Packages: burpsuite  chromeos-kde-git  tlpui
> :: 1 package to upgrade/install.
> 1  aur/tlpui  1:1.5.0.7-1 -> 1:1.6.0-1
> ==> Packages to exclude: (eg: "1 2 3", "1-3", "^4" or repo name)
>  -> Excluding packages may cause partial upgrades and break systems
> ==> 
> AUR Explicit (1): tlpui-1:1.6.0-1
> :: PKGBUILD up to date, skipping download: tlpui
>   1 tlpui                                    (Installed) (Build Files Exist)
> ==> Packages to cleanBuild?
> ==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
> ==> A
> :: Deleting (1/1): /home/[HOME]/.cache/yay/tlpui
> HEAD is now at 51f745f Auto-update to version 1.6.0
> Removing src/
> Removing tlpui-1.6.0.zip
>   1 tlpui                                    (Installed) (Build Files Exist)
> ==> Diffs to show?
> ==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
> ==> N
> ==> Making package: tlpui 1:1.6.0-1 (Wed 06 Sep 2023 11:41:48 PM EDT)
> ==> Retrieving sources...
>   -> Downloading tlpui-1.6.0.zip...
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> 100  619k    0  619k    0     0  1507k      0 --:--:-- --:--:-- --:--:-- 1507k
>   -> Found tlpui.desktop
> ==> WARNING: Skipping verification of source file PGP signatures.
> ==> Validating source files with sha256sums...
>     tlpui-1.6.0.zip ... FAILED
>     tlpui.desktop ... Passed
> ==> ERROR: One or more files did not pass the validity check!
>  -> error downloading sources: /home/[HOME]/.cache/yay/tlpui 
>          context: exit status 1 
>          
> 
> :: (1/1) Parsing SRCINFO: tlpui
> ==> Making package: tlpui 1:1.6.0-1 (Wed 06 Sep 2023 11:41:50 PM EDT)
> ==> Checking runtime dependencies...
> ==> Checking buildtime dependencies...
> ==> Retrieving sources...
>   -> Found tlpui-1.6.0.zip
>   -> Found tlpui.desktop
> ==> Validating source files with sha256sums...
>     tlpui-1.6.0.zip ... FAILED
>     tlpui.desktop ... Passed
> ==> ERROR: One or more files did not pass the validity check!
>  -> error making: tlpui-exit status 1
>  -> Failed to install the following packages. Manual intervention is required:
> tlpui - exit status 1
> ```
You can fix that by changing the sha256sum in the PKGBUILD. (~/.cache/yay/tlpui/PKGBUILD)

The sha256 for 1.6.0 is ffeaec34fc1c7e27f358240faee9dc1935b673204f0d4f0d863486d65eb3db94

Replace the sha256 on line 9 with the new one and then use makepkg -i to install

**Comment by Nambers** [comment]
> > Hi, this is what I got from my Arch `yay -Syyu`
> > ```
> > [sudo] password for [HOME]: 
> > :: Synchronizing package databases...
> >  core                                                             128.1 KiB   104 KiB/s 00:01 [#######################################################] 100%
> >  extra                                                              8.3 MiB  4.44 MiB/s 00:02 [#######################################################] 100%
> >  multilib                                                         143.0 KiB   694 KiB/s 00:00 [#######################################################] 100%
> > :: Searching AUR for updates...
> > :: Searching databases for updates...
> >  -> Flagged Out Of Date AUR Packages: burpsuite  chromeos-kde-git  tlpui
> > :: 1 package to upgrade/install.
> > 1  aur/tlpui  1:1.5.0.7-1 -> 1:1.6.0-1
> > ==> Packages to exclude: (eg: "1 2 3", "1-3", "^4" or repo name)
> >  -> Excluding packages may cause partial upgrades and break systems
> > ==> 
> > AUR Explicit (1): tlpui-1:1.6.0-1
> > :: PKGBUILD up to date, skipping download: tlpui
> >   1 tlpui                                    (Installed) (Build Files Exist)
> > ==> Packages to cleanBuild?
> > ==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
> > ==> A
> > :: Deleting (1/1): /home/[HOME]/.cache/yay/tlpui
> > HEAD is now at 51f745f Auto-update to version 1.6.0
> > Removing src/
> > Removing tlpui-1.6.0.zip
> >   1 tlpui                                    (Installed) (Build Files Exist)
> > ==> Diffs to show?
> > ==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
> > ==> N
> > ==> Making package: tlpui 1:1.6.0-1 (Wed 06 Sep 2023 11:41:48 PM EDT)
> > ==> Retrieving sources...
> >   -> Downloading tlpui-1.6.0.zip...
> >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
> >                                  Dload  Upload   Total   Spent    Left  Speed
> >   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> > 100  619k    0  619k    0     0  1507k      0 --:--:-- --:--:-- --:--:-- 1507k
> >   -> Found tlpui.desktop
> > ==> WARNING: Skipping verification of source file PGP signatures.
> > ==> Validating source files with sha256sums...
> >     tlpui-1.6.0.zip ... FAILED
> >     tlpui.desktop ... Passed
> > ==> ERROR: One or more files did not pass the validity check!
> >  -> error downloading sources: /home/[HOME]/.cache/yay/tlpui 
> >          context: exit status 1 
> >          
> > 
> > :: (1/1) Parsing SRCINFO: tlpui
> > ==> Making package: tlpui 1:1.6.0-1 (Wed 06 Sep 2023 11:41:50 PM EDT)
> > ==> Checking runtime dependencies...
> > ==> Checking buildtime dependencies...
> > ==> Retrieving sources...
> >   -> Found tlpui-1.6.0.zip
> >   -> Found tlpui.desktop
> > ==> Validating source files with sha256sums...
> >     tlpui-1.6.0.zip ... FAILED
> >     tlpui.desktop ... Passed
> > ==> ERROR: One or more files did not pass the validity check!
> >  -> error making: tlpui-exit status 1
> >  -> Failed to install the following packages. Manual intervention is required:
> > tlpui - exit status 1
> > ```
> 
> You can fix that by changing the sha256sum in the PKGBUILD. (~/.cache/yay/tlpui/PKGBUILD)
> 
> The sha256 for 1.6.0 is ffeaec34fc1c7e27f358240faee9dc1935b673204f0d4f0d863486d65eb3db94
> 
> Replace the sha256 on line 9 with the new one and then use makepkg -i to install

Gotcha, thanks!
