### ISSUE TITLE
Ubuntu 22.04 error on start

### ISSUE THREAD

**Issue by pczekalski** [d4nj1/TLPUI#138]
As with the error below, a fresh install on Ubuntu 22.04 (kernel upgraded manually to 6.5) fails to start tlpui (both user and sudo). The terminal version of TLP works fine; the version is 1.6.1:
`$ sudo tlp-stat
--- TLP 1.6.1 --------------------------------------------`

Installed via repo/deb.
`
$ sudo tlpui
Traceback (most recent call last):
  File "/usr/bin/tlpui", line 33, in <module>
    sys.exit(load_entry_point('TLPUI==1.5.0.post5', 'gui_scripts', 'tlpui')())
  File "/usr/lib/python3/dist-packages/tlpui/__main__.py", line 31, in main
    init_tlp_file_config()
  File "/usr/lib/python3/dist-packages/tlpui/file.py", line 40, in init_tlp_file_config
    settings.tlpconfig_defaults = get_tlp_config_defaults(tlpversion)
  File "/usr/lib/python3/dist-packages/tlpui/file.py", line 26, in get_tlp_config_defaults
    tlpconfig_defaults = extract_default_tlp_configs(f"{settings.workdir}/defaults/tlp-{tlpversion}.conf")
  File "/usr/lib/python3/dist-packages/tlpui/filehelper.py", line 46, in extract_default_tlp_configs
    fileopener = open(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3/dist-packages/tlpui/defaults/tlp-1_6.conf'
`

**Comment by d4nj1** [comment]
Hi,
from your stacktrace it shows `TLPUI==1.5.0.post5` so you run an outdated version that is not yet compatible with TLP 1.6.
Where did you install TLPUI from? If you use the PPA from linuxuprising, thats not updated yet:

https://launchpad.net/~linuxuprising/+archive/ubuntu/apps

I would recommend to use the [Flathub](https://flathub.org/apps/com.github.d4nj1.tlpui) one.

**Comment by pczekalski** [comment]
Actually, I was following the guide here:
https://github.com/d4nj1/TLPUI/wiki/Install-instructions#ubuntudebian-family
Version 1.5 seems to be in the PPAs:
```$ apt-cache policy tlpui
tlpui:
  Installed: 1.5.0-5-1~jammy
  Candidate: 1.5.0-5-1~jammy
  Version table:
 *** 1.5.0-5-1~jammy 500
        500 https://ppa.launchpadcontent.net/linuxuprising/apps/ubuntu jammy/main amd64 Packages
        500 https://ppa.launchpadcontent.net/linuxuprising/apps/ubuntu jammy/main i386 Packages
        100 /var/lib/dpkg/status```
