### ISSUE TITLE
"select": unknown values from configfile show up with default value

### ISSUE THREAD

**Issue by linrunner** [d4nj1/TLPUI#14]
Example:

CPU_SCALING_GOVERNOR_ON_BAT=nodemand shows as "powersave" in the GUI

However, i have no idea yet how to handle this in a user friendly manner.

**Comment by d4nj1** [comment]
How about to show config as an entry field with some kind of visible notification about unkown configuration and possible values? Would this help in your opinion?

**Comment by linrunner** [comment]
Do you mean an entry field _in addition_ to the dropdown listbox? Then yes.

**Comment by d4nj1** [comment]
Sufficient warning added. Should be ok for now.
