### ISSUE TITLE
Error in css.py. Item 0: Must be number, not str

### ISSUE THREAD

**Issue by jrequejo** [d4nj1/TLPUI#147]
Hi, 
 Upon running python3 -m tlpui I get the following error:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/jri/TLPUI/tlpui/__main__.py", line 16, in <module>
    get_css_provider(),
  File "/home/jri/TLPUI/tlpui/css.py", line 13, in get_css_provider
    cssprovider.load_from_data(cssdata)
TypeError: Item 0: Must be number, not str

TLP is version 1.6 up and running and python is version 3.10.12
--- TLP 1.6.1 --------------------------------------------

+++ System Info
System         = HP SBKPF HP EliteBook 640 14 inch G9 Notebook PC
BIOS           = U75 Ver. 01.09.02
EC Firmware    = 7.103
OS Release     = Ubuntu 22.04.4 LTS
Kernel         = 6.5.0-26-generic #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Mar 12 10:22:43 UTC 2 x86_64
/proc/cmdline  = BOOT_IMAGE=/boot/vmlinuz-6.5.0-26-generic root=UUID=a4f858cd-8fa1-4201-8679-6cf679f9de51 ro quiet splash vt.handoff=7
Init system    = systemd v249 (249.11-0ubuntu3.12)
Boot mode      = UEFI
Suspend mode   = [s2idle] deep

+++ TLP Status
State          = enabled
RDW state      = enabled
Last run       = 14:22:21, 13 sec(s) ago
Mode           = battery
Power source   = battery

What can the reason be?
Thanks

**Comment by d4nj1** [comment]
Fixed in https://github.com/d4nj1/TLPUI/releases/tag/tlpui-1.6.5
