### ISSUE TITLE
Generic icon shown on GNOME (wayland) overview and dash

### ISSUE THREAD

**Issue by badshah400** [d4nj1/TLPUI#149]
TLP UI shows a generic icon for open application instances on the GNOME overview (wayland) and dash (see screenshot) because it sets an app ID that is different from the name of the `.desktop` file.

Fix is straightforward:

```diff
diff --git a/tlpui/__main__.py b/tlpui/__main__.py
index a328604..d926d77 100755
--- a/tlpui/__main__.py
+++ b/tlpui/__main__.py
@@ -18,7 +18,7 @@ Gtk.StyleContext.add_provider_for_screen(
 )
 
 # Set window properties
-GLib.set_prgname('tlp-ui')
+GLib.set_prgname('tlpui')
 Gdk.set_program_class('Tlp-UI')
 
 # Apply custom scalable icons to icon theme
```

Many thanks for the great app!

![tlpui](https://github.com/d4nj1/TLPUI/assets/3532467/a1fb600c-312f-469c-8279-db1347eae3c1)

**Comment by Integral-Tech** [comment]
I am using KDE Plasma on Wayland. The same issue as yours.

**Comment by badshah400** [comment]
So... you just took my, admittedly straightforward, patch and simply put your name on the commit? Anyway, as long as it gets merged, fine by me, I guess.

**Comment by Integral-Tech** [comment]
> So... you just took my, admittedly straightforward, patch and simply put your name on the commit? Anyway, as long as it gets merged, fine by me, I guess.

I am sorry I forgot to put your name on the commit. I have just changed the commit author to you.

**Comment by badshah400** [comment]
Thanks a bunch and please accept my apologies for previous salty message.

**Comment by d4nj1** [comment]
This is merged in will be in the next release. Thanks for your contribution.
