### ISSUE TITLE
Left align all input fields

### ISSUE THREAD

**Issue by linrunner** [d4nj1/TLPUI#15]
Current situation: 
* Alignment varies whether there is an AC/BAT icon or not
* No alignment for some tabs, especially Radio, Radio Device Wizard

Proposal:
* Left align all fields for all tabs to the same position, for example at 2/3 of the dialog width

**Comment by d4nj1** [comment]
Alignments updated, see:
https://github.com/d4nj1/TLPUI/commit/afef79fe798d79c285d8713c133db29fd1ba8117

**Comment by linrunner** [comment]
OK
