### ISSUE TITLE
Thanks for making this!

### ISSUE THREAD

**Issue by soisyourface** [d4nj1/TLPUI#155]
As a lenovo(x1 carbon 12)-fedora(40) user I just learned about TLP and was feeling pretty exhausted at all of the config.
Then I found this awesome tool to help with all of that stuff!

Not certain if this is protocol to create an issue to say, "thanks", but here is an issue where I thought I'd say "thanks for making such a useful tool".

**Comment by d4nj1** [comment]
You're welcome. Thanks for the appreciation.
