### ISSUE TITLE
Cannot run on elementary os Loki

### ISSUE THREAD

**Issue by ghost** [d4nj1/TLPUI#18]
when trying to run TLPUI with ./tlpui.py
I get this error message :+1: 
`Traceback (most recent call last):
  File "./TLP/tlpui.py", line 10, in <module>
    from mainui import create_main_box, close_window
  File "/home/harisvsulaiman/TLP/mainui.py", line 6, in <module>
    from configui import create_config_box
  File "/home/harisvsulaiman/TLP/configui.py", line 13, in <module>
    trans = gettext.translation('configdescriptions', 'lang/', languages=['de_DE', 'en_EN'])
  File "/usr/lib/python3.5/gettext.py", line 432, in translation
    raise OSError(ENOENT, 'No translation file found for domain', domain)
FileNotFoundError: [Errno 2] No translation file found for domain: 'configdescriptions'
`

**Comment by d4nj1** [comment]
Hi,
the translation folder is added as a relative path to the python program so the python script must be run inside your TLP folder.

> cd TLP
> ./tlpui

instead of

> ./TLP/tlpui.py

Hope this solves the issue for now. I will take care of relative path issues in a future release.
Thanks for report.

**Comment by harisvsulaiman** [comment]
yes i did that

**Comment by d4nj1** [comment]
Hmm, so this is not fixed I guess.
I will look deeper into this. Can you post me you ouput from 

> locale

? Thanks

**Comment by d4nj1** [comment]
Should be fixed now.
