### ISSUE TITLE
fetch tlp-stats works only with non-graphical sudo

### ISSUE THREAD

**Issue by amateusz** [d4nj1/TLPUI#25]
The program is supposed to call `tlp-stat` with a graphical sudo (thus `get_graphical_sudo()` in [statui.py](https://github.com/d4nj1/TLPUI/blob/master/statui.py)).
But for me only the regular `sudo` works when called from within the program. I'd commit, but it seems to work for everyone else as it is. Why is that ?
I'm on manjaro linux (arch based).

**Comment by d4nj1** [comment]
Hi,
I don't quite understand what does not work? Do you get any output in the stat-ui-view when trying to fetch stats? Do you have one of the following installed: pkexec, gksu, gksudo, kdesu or kdesudo?

**Comment by d4nj1** [comment]
I haven't heared anything from you for a while now, so I close this issue.
If this is still a bug for you please reopen.
