### ISSUE TITLE
JSON schema 1.1

### ISSUE THREAD

**Issue by bigforcegun** [d4nj1/TLPUI#26]
TLP have some update tonight. 
`
FileNotFoundError: [Errno 2] Нет такого файла или каталога: '/home/bigforcegun/source/TLPUI/configschema/1_1.json'
`

Can we help with new settings schema?

**Comment by d4nj1** [comment]
Yes, I know this. As I had a lot of work these days I was not able to add schema for TLP version 1.1
Hopefully I will do this tonight. Will report back when done.

**Comment by d4nj1** [comment]
Schema 1.1 support added. Translation were not updated as this takes some more effort. It will follow the next days.
