### ISSUE TITLE
About adding some features

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [d4nj1/TLPUI#3]
Hi! I am author of the same project tlp-gui https://github.com/ZaMaZaN4iK/tlp-gui . And only today i had seen your beautiful utility. I think, that your utilite is much better, than my. Maybe, my code help you to add some features in your tlpui :
0) Add profiles in TLP. Only two profiles (AC and battery) is very little list of profiles. Pls add more profiles and feature of creating new profiles in the program.
1) Add support system tray and switching between profiles in tray. It is very useful function in my opinion.
2) Add checker for existing profiles for TLP. User can edit config with Kate, for example and make a mistake. And tlpui can check profile and show warning, for example.
etc.

Sorry for my poor English.
Good luck with your program!

**Comment by d4nj1** [comment]
Hi and thanks for your appreciation. Nice to hear that you like the tool.
I will take a look on your project and evaluate if there are features I can adapt.
Here are my thoughts on your suggestions:

> 0) Add profiles in TLP. Only two profiles (AC and battery) is very little list of profiles. Pls add more profiles and feature of creating new profiles in the program.

Is this really needed? I think most configuration parameters can be changed whether the device is on ac or battery mode. I will talk about this idea with the initial tlp author.

> 1) Add support system tray and switching between profiles in tray. It is very useful function in my opinion.

See answer for 0). If profiles are a feature to implement this would be a good feature. I will keep that in mind.

> 2) Add checker for existing profiles for TLP. User can edit config with Kate, for example and make a mistake. And tlpui can check profile and show warning, for example. etc.

Actually my TLP-UI has the most config values pre defined. This should avoid bad config input values. The UI currently fails on a miss configuration. But you are right. All input config values should have a validity check. I will see if I can add some kind of pattern matcher.

Thanks for you ideas and kind regards.

**Comment by d4nj1** [comment]
Hi.
For 0) and 1) there is a "TLP Indicator for Unity". There is even a screenshot. Look here:

http://askubuntu.com/questions/285434/is-there-a-power-saving-application-similar-to-jupiter
https://github.com/silverjam/Sysmods/blob/master/scripts/indicator-TLP.py

For 2) there will come an update in the near future, see Issue #14.
