### ISSUE TITLE
Fetch Simple Stats error

### ISSUE THREAD

**Issue by moocan** [d4nj1/TLPUI#34]
Hello,

I have this error when I'm trying to fetch simple stats : 
`File "/..../TLPUI-master/tlpui/statui.py", line 19, in fetch_simple_stats
    tlpstat = check_output(["tlp-stat", "-g", "-r", "-t", "-c", "-s", "-u"]).decode(sys.stdout.encoding)
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['tlp-stat', '-g', '-r', '-t', '-c', '-s', '-u']' returned non-zero exit status 3.`
... and nothing is happening.

Fetching complete stats works well. An authentication is prompted.

Kind Regards

**Comment by d4nj1** [comment]
Hi,
can you tell me which version of **tlp** you use? You can read it from terminal with:
`tlp-stat -c`
Could you also post me the output of:
`tlp-stat -h`

It might be that a parameter for simple stats is not available for the **tlp** version you use. If this is the case I will solve this asap.

Thanks in advance

**Comment by moocan** [comment]
Hello,

Of course no problem.
I'am using ubuntu stock tlp.
Here is the result of commands 
- `$ tlp-stat -c`

>  --- TLP 0.9 --------------------------------------------
> 
> +++ Configured Settings: /etc/default/tlp
> TLP_ENABLE=1
> TLP_DEFAULT_MODE=AC
> DISK_IDLE_SECS_ON_AC=0
> DISK_IDLE_SECS_ON_BAT=2
> MAX_LOST_WORK_SECS_ON_AC=15
> MAX_LOST_WORK_SECS_ON_BAT=60
> CPU_SCALING_GOVERNOR_ON_AC=performance
> CPU_SCALING_GOVERNOR_ON_BAT=powersave
> SCHED_POWERSAVE_ON_AC=0
> SCHED_POWERSAVE_ON_BAT=1
> NMI_WATCHDOG=0
> ENERGY_PERF_POLICY_ON_AC=performance
> ENERGY_PERF_POLICY_ON_BAT=powersave
> DISK_DEVICES="sda sdb"
> DISK_APM_LEVEL_ON_AC="254 254"
> DISK_APM_LEVEL_ON_BAT="128 128"
> SATA_LINKPWR_ON_AC=max_performance
> SATA_LINKPWR_ON_BAT=min_power
> AHCI_RUNTIME_PM_TIMEOUT=15
> PCIE_ASPM_ON_AC=performance
> PCIE_ASPM_ON_BAT=powersave
> RADEON_POWER_PROFILE_ON_AC=high
> RADEON_POWER_PROFILE_ON_BAT=low
> RADEON_DPM_STATE_ON_AC=performance
> RADEON_DPM_STATE_ON_BAT=battery
> RADEON_DPM_PERF_LEVEL_ON_AC=auto
> RADEON_DPM_PERF_LEVEL_ON_BAT=auto
> WIFI_PWR_ON_AC=off
> WIFI_PWR_ON_BAT=on
> WOL_DISABLE=Y
> SOUND_POWER_SAVE_ON_AC=0
> SOUND_POWER_SAVE_ON_BAT=1
> SOUND_POWER_SAVE_CONTROLLER=Y
> BAY_POWEROFF_ON_BAT=0
> BAY_DEVICE="sr0"
> RUNTIME_PM_ON_AC=on
> RUNTIME_PM_ON_BAT=auto
> RUNTIME_PM_ALL=1
> RUNTIME_PM_DRIVER_BLACKLIST="radeon nouveau"
> USB_AUTOSUSPEND=1
> USB_BLACKLIST_WWAN=1
> RESTORE_DEVICE_STATE_ON_STARTUP=0
> DEVICES_TO_DISABLE_ON_BAT_NOT_IN_USE="bluetooth wifi wwan"

- `tlp-stat -h`

> Usage: tlp-stat [ -b | --battery   | -c | --config |
>                   -d | --disk      | -e | --pcie   |
>                   -p | --processor | -r | --rfkill |
>                   -s | --system    | -t | --temp   |
>                   -u | --usb       | -w | --warn   |
>                   -P | --pev       | -T | --trace  |
>                   -v | --verbose ]

Kind Regards
Moo

**Comment by d4nj1** [comment]
Hi,
bug should be fixed now. Problem was as I suggested. The parameter **-g** was introduced in TLP version 1.0 and is therefore now available for your installed TLP version (see https://github.com/linrunner/TLP/blob/master/changelog for details).

Please update to latest TLPUI master.

Thanks for your report
