### ISSUE TITLE
WOL setting wrong

### ISSUE THREAD

**Issue by owenversteeg** [d4nj1/TLPUI#35]
I recently installed tlpui and I'm loving it. Great work!

I've found a little bug though: if you turn the switch for WOL_DISABLE to "on" (default off), it actually does not disable WOL but instead appears to enable it. 

Specifically: when the switch is on, WOL_DISABLE is set to "N", and various documentation seems to indicate that will cause wake-on-LAN to be enabled.

**Comment by d4nj1** [comment]
Hi,
can you tell me which version of TLP you use?

**Comment by d4nj1** [comment]
This was definitely a bug in the UI. Switched on/off behaviour.

Thanks for reporting.
