### ISSUE TITLE
configui.py bug

### ISSUE THREAD

**Issue by wangxa** [d4nj1/TLPUI#36]
In `configui.py` line 120: `tlpobject = settings.tlpconfig[configname]`

If `configname` is not in `settings.tlpconfig`, then you will fail in creating GUI with the error message like `KeyError: 'USB_BLACKLIST_PRINTER'`. Move the statement into try...except block.

**Comment by d4nj1** [comment]
Actually there is a check for this in the line below which is not working as expected. Will fix this ASAP.

**Comment by d4nj1** [comment]
Bug should be fixed. Please update to latest master.

Thanks for reporting.
