### ISSUE TITLE
TLPUI is not requesting root permissions to write to file on Wayland

### ISSUE THREAD

**Issue by Pant** [d4nj1/TLPUI#38]
I use Fedora 28 and when i run the command `python3 -m tlpui` the window comes up as it should. Problem is when i am trying to save my changes nothing happens, it doesn't request root password through `pkexec`, the application doesn't respond and I have to force end it.

If I run the following command everything works (workaround): `pkexec cd ~/Downloads/TLPUI && python3 -m tlpui`

(Very nice app btw!)

**Comment by d4nj1** [comment]
Hi,
I'm currently trying to reproduce this behaviour. Will come back to you with a finding hopefully.

**Comment by d4nj1** [comment]
I added a possible fix. Please check out current master and try again.
Hopefully the problem is solved now.

με τις καλύτερες ευχές από Γερμανία ;)

**Comment by d4nj1** [comment]
Hi,
can you verify if the problem has been solved?

Thanks in advance

**Comment by Pant** [comment]
Sorry for being away for a while.
It works as it is supposed to now. 

Ευχαριστώ και ανταποδίδω από Ελλάδα :)
