### ISSUE TITLE
 installation problem

### ISSUE THREAD

**Issue by andreadegiorgi91** [d4nj1/TLPUI#39]
Hello. I was trying to install TLPUI only that the following appears in the terminal:

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/andrea/Scaricati/TLPUI-master/tlpui/__main__.py", line 8, in <module>
    from . import settings
  File "/home/andrea/Scaricati/TLPUI-master/tlpui/settings.py", line 53, in <module>
    tlpconfigfile = config['default']['tlpconfigfile']
  File "/usr/lib/python3.5/configparser.py", line 1230, in __getitem__
    raise KeyError(key)
KeyError: 'tlpconfigfile'

What could be the problem?
I can not tell if Gtk3 libs is installed. How can I check?

**Comment by d4nj1** [comment]
Hi, could you check you user config file in **/home/andrea/.config/tlpui/tlpui.cfg**?
It should be like this:

```
[default]
language = en_EN
tlpconfigfile = /etc/default/tlp
activecategorie = 7
windowxsize = 900
windowysize = 600
```

Maybee you have an old unsupported version of this file.

Did you ever run tlpui before? Could you paste your config here?

Kind regards

**Comment by andreadegiorgi91** [comment]
No, I've never had TLPUI. My tlpui.cfg file contained only the string `[default]`. So I manually added the strings you indicated and TLPUI was started. Thanks for the reply.

**Comment by d4nj1** [comment]
Thanks for the feedback.
Seems I have to improve on the config creation/updating behaviour. Will keep this issue open until this task is done.

**Comment by d4nj1** [comment]
Improved the config file handling. Added some validation and restoring of default values when config parameters not as expected. Also added some unittests just in case. ;)
