### ISSUE TITLE
Group config items

### ISSUE THREAD

**Issue by linrunner** [d4nj1/TLPUI#4]
Situation: many of TLP's configuration items come in pairs e.g.

```
SOMETHING_ON_AC
SOMETHING_ON_BAT
```

some even in quadruples like CPU_SCALING_MIN/MAX_FREQ_ON_AC/BAT. These tuples _always share_ a long description in **/etc/default/tlp**.

TLPUI currently doesn't know about these tuples and just duplicates the long descriptions for all items. 

Problems of the current appoach:
- Uses _very much_ UI space 
- Difficult for the user to visually recognize the relationship between the parts

Solution: 
- Implement grouping in configcategories.json
- Multiple items can share one "title" (new attribute) and "description"
- Place values not below but after "id" in UI

The resulting UI could look as follows

```
------------------------------------------------------
Title

SOMETHING_ON_AC   [ value ]
SOMETHING_ON_BAT  [ value ]

Long description
```

**Comment by d4nj1** [comment]
Please check if configs are grouped correctly or anything is missing.

**Comment by linrunner** [comment]
Works so far. 

We need titles for single items too and i suggest to name the attribute "title" for both.

**Comment by d4nj1** [comment]
Group and config titles are available and translateable. See Issue #11. I think this can be closed now.
