### ISSUE TITLE
x window props missing

### ISSUE THREAD

**Issue by cortopy** [d4nj1/TLPUI#45]
It doesn't look like the window props are set in x. My main issue is with `WM_CLASS(STRING) = "__main__.py", "__main__.py"`. [i3wm](https://i3wm.org/) users rely on information like that one to configure things like whether the window should be floating.

When inspecting the TLPUI window with `xprop` this is the information displayed:

```
_NET_WM_DESKTOP(CARDINAL) = 1
_NET_WM_STATE(ATOM) = 
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		window id # of group leader: 0x4e00001
_GTK_THEME_VARIANT(UTF8_STRING) = 
XdndAware(ATOM) = BITMAP
_NET_WM_OPAQUE_REGION(CARDINAL) = 2, 0, 1890, 2, 0, 2, 1894, 2074
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 81788939, 81788940
_NET_WM_USER_TIME(CARDINAL) = 33685065
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x4e0000a
WM_CLIENT_LEADER(WINDOW): window id # 0x4e00001
_NET_WM_PID(CARDINAL) = 13329
WM_LOCALE_NAME(STRING) = "en_GB.UTF-8"
WM_CLIENT_MACHINE(STRING) = "work"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 434 by 779
		program specified base size: 0 by 0
		window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "__main__.py", "__main__.py"
WM_ICON_NAME(STRING) = "TLP-UI"
_NET_WM_ICON_NAME(UTF8_STRING) = "TLP-UI"
WM_NAME(STRING) = "TLP-UI"
_NET_WM_NAME(UTF8_STRING) = "TLP-UI"
```

**Comment by d4nj1** [comment]
Hi,
I could override wmclass with:

`window.set_wmclass('tlpui', 'TLP-UI')
`

which would then result in following WM_CLASS xprops:

`WM_CLASS(STRING) = "tlpui", "TLP-UI"
`

The problem to this is, that this method is already obsoleted and should not be used in newly written code, see https://developer.gnome.org/gtk3/stable/GtkWindow.html#gtk-window-set-wmclass

I will try to find a non-obsolete solution to avoid this quick-fix. Please be patient as this seems to take a little longer.

Kind regards

**Comment by d4nj1** [comment]
Hi,
if you start TLPUI through a **.desktop** file you can add the key **StartupWMClass** to set a custom **WL_CLASS** xprop:

`StartupWMClass=tlpui`

Does this help you?

**Comment by cortopy** [comment]
thank you for such a speedy response!! I'll try that

**Comment by cortopy** [comment]
I just tried amending my file to the following:

```
[Desktop Entry]
Encoding=UTF-8
Name=TLPUI
Comment=A GTK user interface for TLP
Keywords=TLP TLP-UI
Exec=tlpui
Terminal=false
Type=Application
Categories=Settings;HardwareSettings
StartupWMClass=tlpui
```

but when I do `xprop WM_CLASS` I get the same result

**Comment by d4nj1** [comment]
Hi,
I think documentation is a bit misleading:

`StartupWMClass=STRING`

`If true, it is KNOWN that the application will map at least one
window with the given string as its WM class or WM name hint.`

Seems like **StartupWMClass** is a only the mapper for **.desktop** files to combine the application name with the defined xprops.

Sorry for my misunderstanding. I'm on it to bring up a persistent fix for you.

Kind regards

**Comment by cortopy** [comment]
Yes, I also thought it's quite confusing behaviour. Many thanks!

**Comment by d4nj1** [comment]
Hi,
sorry for late response.

Would it be enough if you have set **wmclass_class** and not **wmclass_name**?
I mean something like this:

`WM_CLASS(STRING) = "__main__.py", "tlpui"`

I could set this via GDK like:

`Gdk.set_program_class('tlpui')`

This is not obsolete and sets the **WM_CLASS** for the main window and all **tlpui** child-windows.

**Comment by d4nj1** [comment]
I just added the required WM_CLASS parameters. When you check out latest master you should get:

`WM_CLASS(STRING) = "tlp-ui", "Tlp-UI"`

This should be what you requested. Please report back if it works for you now.

Thanks in advance

**Comment by cortopy** [comment]
working like a charm!! thanks so much!!
