### ISSUE TITLE
What are the requirements?

### ISSUE THREAD

**Issue by thenets** [d4nj1/TLPUI#46]
Hi @d4nj1,

I'm trying to help with the development but I can't even install the project. Can you help me to setup me environment?

And what are the requirements? I try to install and I got this error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/luiz/Projects/TLPUI/tlpui/__main__.py", line 2, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
```

**Comment by d4nj1** [comment]
Hi,
I think that depends on your system/distribution. Please have a look at https://pygobject.readthedocs.io/en/latest/getting_started.html

Does this help?

**Comment by bpunktm** [comment]
> Does this help?

No. I have the necessary dependencies installed, but it doesn't run.

**Comment by d4nj1** [comment]
@bpunktm
Can you provide more information on how you run tlpui and share some kind of error output here?

**Comment by d4nj1** [comment]
Seems to be fixed as there was no feedback.
