### ISSUE TITLE
Import config schema from TLP

### ISSUE THREAD

**Issue by linrunner** [d4nj1/TLPUI#5]
Situation: currently TLPUI itself provides the schema that declares all of TLP's config values e.g.  **configcategories.json**

Problem of the current approach:
* New releases of TLP containing new config items necessitate new TLPUI release to update the schema

Solution:

1. Look into **/usr/share/tlp-pm/** for a schema provided by TLP
1. If none found, use TLPUI's own schema (to facilitate the migration)

Suggestion:
* change **configcategories.json** to a more intuitive **configschema.json**

**Comment by d4nj1** [comment]
Fixed.
