### ISSUE TITLE
Typo in DISC_IDLE_SECS description with enEn localization

### ISSUE THREAD

**Issue by keybreak** [d4nj1/TLPUI#50]
Double to here:
![Image of Yaktocat](https://i.imgur.com/dPyczKr.png)

**Comment by keybreak** [comment]
https://github.com/d4nj1/TLPUI

Also on the screenshot here :laughing:

**Comment by d4nj1** [comment]
Hi @keybreak,
and thanks for reporting. This is totally not acceptable! :sweat_smile: 
Please check out latest master with fixed typo.

**Comment by keybreak** [comment]
Hi, thx for fixing it, after all we're here to make our World a little better :)

> This is totally not acceptable! sweat_smile

Yeah, i know! Like i've said...
I know few guys commited suicide because of this utterly inappropriate error! :smile:
