### ISSUE TITLE
configschema/1_2_1.json not found

### ISSUE THREAD

**Issue by Pazystamas** [d4nj1/TLPUI#51]
Instaling on Ubuntu 18.10 and got error FileNotFoundError: '/home/myuser/TLPUI/tlpui/configschema/1_2_1.json'. There is only 1_2.json file in configschema folder.

**Comment by BruceZhang1993** [comment]
Same here. Please add tlp 1.2.1 config schema

**Comment by d4nj1** [comment]
TLP 1.2.1 was released yesterday evening with patch-version applied to version number. Will fix this ASAP.

**Comment by d4nj1** [comment]
As there were no configschema changes for TLP 1.2.1 we only look at the major and minor version for configschema selection.
Please check out latest master and enjoy. :slightly_smiling_face:
