### ISSUE TITLE
Simple Stat runs only with sudo

### ISSUE THREAD

**Issue by lousapetr** [d4nj1/TLPUI#55]
The button Simple at Stats tab does not work for me. I get the same error as in #34 

```
Traceback (most recent call last):
  File "/home/lousapetr/bin/TLPUI-master/tlpui/statui.py", line 24, in fetch_simple_stats
    tlpstat = check_output(simple_stat_command, stderr=STDOUT).decode(sys.stdout.encoding)
  File "/usr/lib64/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['tlp-stat', '-g', '-r', '-t', '-c', '-s', '-u']' returned non-zero exit status 1.
```
The Complete Stats work perfectly.

So, I tried to run the command
```
$ tlp-stat -g -r -t -c -s -u
Error: missing root privilege.
```

Finally, I resolved the issue by adding `sudo` to the Simple Stats as well. Line 24 in statui.py:
```
    sudo_cmd = get_graphical_sudo()
    tlpstat = check_output([sudo_cmd]+simple_stat_command, stderr=STDOUT).decode(sys.stdout.encoding)
```

The only issue remaining is that even Simple Stats ask for my password.

**Comment by lousapetr** [comment]
Btw, TLP version is 1.2.2, the build of TLPUI is of 18.3.2019.

**Comment by d4nj1** [comment]
Hi and thanks for reporting.
Seems like the **-g** option does require extra permissions from now on. I removed it from simple stats as this does not make sense anymore. Fix is in latest master now.

Kind regards
