### ISSUE TITLE
Darker icons

### ISSUE THREAD

**Issue by giovannicaligaris** [d4nj1/TLPUI#57]
The icons on the app are too light is hard to see it, they need to be a bit darker.

**Comment by d4nj1** [comment]
Hi,
there is something in preparation for this. I had in mind to do this dynamically by looking at the base GTK color and then change icon darkness by this. As this is not as trivial as I thought it would be I currently tend towards a menu option where you can select from a set of pre defined icons.

Sadly I am currently very busy privately so I can't tell you any ETA on this. Please be patient.

**Comment by giovannicaligaris** [comment]
The best way to do this is to convert all icons to symbolic icons. That way when the theme changes it will adjust automatically.

Usually for elementary OS and GNOME, all of the tray icons tend to be symbolic for this reason.

**Comment by d4nj1** [comment]
Hi,
I search the web and it seems like it could be possible to load symbolic icons from svg. Will try this out when I discover some free time.

**Comment by d4nj1** [comment]
Hi @giovannicaligaris,
check out the latest version and try with your theme. Category icons should behave as expected now. Please report back if possible.

**Comment by yochananmarqos** [comment]
Now there are no icons at all:

![Screenshot from 2020-01-21 13-08-14](https://user-images.githubusercontent.com/5437803/72839258-3192ab00-3c4f-11ea-94d0-2850f49072ca.png)

Manjaro GNOME using `tlpui-git` AUR package
Adwaita-maia-dark GTK theme
Papirus-Dark-Maia icon theme

**Comment by d4nj1** [comment]
Thanks @yochananmarqos for feedback.
This behaviour is strange as it works on my machine without any issue.
I followed https://developer.gnome.org/ThemedIcons/ but maybe I chose a solution that does apply in general. Will try to solve this. Otherwise I will role back soon.

**Comment by d4nj1** [comment]
Hi @yochananmarqos,
can you verify that you have librsvg installed?

Thanks in advance

**Comment by giovannicaligaris** [comment]
I just tested and it looks great!

**Comment by yochananmarqos** [comment]
@d4nj1 Yes, I have `librsvg` installed.

**Comment by d4nj1** [comment]
Hi @yochananmarqos,
I added a fallback for missing icons to load them manually. That means if the icons can not be applied to the icon theme (as it seems to be the case for you), they are loaded without beeing adopted the current theme colors.
I am sorry that this might not be satisfying for you but I could not reproduce the behaviour you are facing on my machine.

Lastly I would like two things for you to verify:

1. Check if you see all icons in the UI now
2. Check if **hicolor-icon-theme** is installed

Awaiting your feedback.

**Comment by yochananmarqos** [comment]
No difference with the latest commit, unfortunately. Yes, I have `hicolor-icon-theme` installed.

**Comment by d4nj1** [comment]
Hi @yochananmarqos,
I updated the **setup.py** script so it adds all the required images to it's **package_data**.
Please rebuild after checking out latest master and report back.

Thanks in advance

**Comment by yochananmarqos** [comment]
@d4nj1 That did the trick, thank you.

**Comment by d4nj1** [comment]
Issue resolved.
