### ISSUE TITLE
[Advance Notice] New configuration scheme in TLP 1.3 

### ISSUE THREAD

**Issue by linrunner** [d4nj1/TLPUI#59]
Hi,

i really don't want to pull away the carpet under TLPUI's feet, so some information in advance.

Configuration is split into several files, read in the following order:
1. **/usr/share/tlp/defaults.conf** – Intrinsic defaults 
2. **/etc/tlp.conf.d/*.conf** – Drop-in customizations
3. **/etc/tlp.conf** – User configuration

In case of identical parameters, the last occurence has precedence.

Reading and merging the files is done by **tlp-readconfs**, feel free to make use of it.

In addition tlp subcommands init, auto, start, bat, ac, suspend
and resume will write the merged configuration to **/run/tlp/run.conf**.

There is no release date for 1.3 yet and i would be grateful for your comments and suggestions. Note that the feature isn't even in the master branch yet.

References:
* https://github.com/linrunner/TLP/commits/conf.d
* https://github.com/linrunner/TLP/issues/432
* https://github.com/linrunner/TLP/pull/435

Grüsse / Regards, Thomas

**Comment by d4nj1** [comment]
Hi Thomas,
thanks for the heads-up. I have been curious when this would be come as I saw the discussions you had with people demanding this. :wink: 

Basically I like the idea of having one user configuration file where only changes to the defaults are stored. Here some questions regarding the upcoming changes for TLPUI:

1. Configuration changes in the UI should only result in writing to **/etc/tlp.conf**?
2. Will the configuration file paths be the same for most linux distributions?
3. Should drop-in customizations be selectable from the user? In terms of changing/activating/deactivating preferences on the fly?
4. When will **/run/tlp/run.conf** be written? On **tlp** service restart/reload? Should the UI have a trigger for this?

Thanks for **tlp-readconfs**. I might really be using it. At least for validating loaded configuration.

Kind regards,

Daniel

**Comment by linrunner** [comment]
Good to know, you're relaxed about this :-).

1. Exact.

2. I hope so. /etc/default/ is (a) Debian-specfic and (b) arose out of ignorance on my part, because it's about a daemon's start configuration and TLP isn't a daemon. So /etc/tlp.conf would have been the logical choice form the beginning. Gentoo already uses it instead of /etc/default/tlp.

3. Yes! Good idea!

4. When will /run/tlp/run.conf be written? On tlp service restart/reload? 

A `systemctl restart tlp` will  execute `tlp init stop`, `tlp init start` and thus implicitly writes run.conf as said above
> tlp subcommands init, auto, start, bat, ac, suspend and resume will write

BUT: restarting the service is not the right way to apply changed settings. 
PLEASE use `tlp start` for that purpose.

4. Should the UI have a trigger for this?

I'm not sure what you mean: 

- If you want to refresh TLP after config changes, then see above.
- If TLPUI should notice an newly written run.conf, then i'd try inotify

**Comment by d4nj1** [comment]
> BUT, restarting the service is not the right way to apply changed settings. A service restart could cut your wifi (depending on the config), that's not what users expect i guess.

> PLEASE use `tlp start` for that purpose.

Thanks for clarifying.

> * If you want to refresh TLP after config changes, then see above.
> * If TLPUI should notice an newly written run.conf, then i'd try inotify

I am asking myself if `tlp start` should be executed automatically when saving configuration changes in UI. I personally would expect the UI to do this. What do you say?

**Comment by linrunner** [comment]
I'd also expect this behaviour. However, it is to be considered, that `tlp start`takes 1-2 seconds to complete.

**Comment by joakim-tjernlund** [comment]
Need this change now, please ...

**Comment by d4nj1** [comment]
Hi @linrunner,
I currently try to adopt configuration changes to TLP 1.3 but struggle a bit to provide backwards compatibility.
One thing I noticed is that there seem to be no way to disable any "intrinsic defaults" other by overriding it with a disabled Drop-in configuration as all configuration items in "/etc/tlp.conf" are disabled by default.
Is this an issue or a desired behaviour?

Thanks in advance

**Comment by linrunner** [comment]
Actually the basic behaviour didn't change from < 1.3. What has changed is that everything previously enabled in **/etc/default/tlp** became an intrinsic.

Disable by

       PARAM=""

in **tlp.conf** or **/etc/tlp.d/*.conf**.

**Comment by linrunner** [comment]
ps. to determine the actual intrinsics, you can parse **/usr/share/tlp/defaults.conf**.

**Comment by d4nj1** [comment]
> Actually the basic behaviour didn't change from < 1.3. What has changed is that everything previously enabled in **/etc/default/tlp** became an intrinsic.
> 
> Disable by
> 
> ```
>    PARAM=""
> ```
> 
> in **tlp.conf** or **/etc/tlp.d/*.conf**.

So it means that **quoted empty**

`
PARAM=""
`

is equal to **unquoted empty**

`
PARAM=
`

is equal to **sharp** ?

`
#PARAM="VALUE"
`

Questions:

- Should there really be multiple ways of displaying/storing deactivated values? I would not like to confuse users when doing changes manually or looking at the **/etc/tlp.conf**.
- Can all values be quoted then?

---

Another problem is that some default values are not defined anywhere other than in **/etc/tlp.conf**:

Currently UI elements should have a default value in any case to display value selection correctly.

Take `#CPU_MAX_PERF_ON_AC=100` as an example.

It has no intrinsic default in **/usr/share/tlp/defaults.conf** but when activated in the UI, the visual element should have a default value to be displayed correctly.

Question:

- Should there be defaults for deactivated values like currently defined in **/etc/tlp.conf** ?

---

I would appreciate you feedback @linrunner

**Comment by padok** [comment]
Arch Linux has just added tlp 1.3 to the official repositories. (2020-02-04 17:19 UTC)
https://www.archlinux.org/packages/community/any/tlp/

Since then tlpui is broken for all arch linux users including me.

> Just wanted to draw attention to the recent development.

**Comment by linrunner** [comment]
> So it means that **quoted empty**
> `PARAM=""`
> is equal to **unquoted empty**
> `PARAM=`

Yes. Unquoted empty is equivalent to quoted empty.

> is equal to **sharp** ? 
> `#PARAM="VALUE"`

No, It depends:

1. Parameters with a default can only be disabled by "* empty"
2. Parameters without default can be disabled by "sharp"

This behaviour didn't change from 1.2. There was an internal change only: the intrinsic defaults are in /usr/share/tlp/defaults.conf now instead of in the code.

>  Should there really be multiple ways of displaying/storing deactivated values? I would not like to confuse users when doing changes manually or looking at the **/etc/tlp.conf**.

Yes. See above.

>  Can all values be quoted then?

Yes. tlp-stat -c shows them like this after parsing.

> Another problem is that some default values are not defined anywhere other than in **/etc/tlp.conf**:
> Currently UI elements should have a default value in any case to display value selection correctly.
> Take `#CPU_MAX_PERF_ON_AC=100` as an example.
> It has no intrinsic default in **/usr/share/tlp/defaults.conf** but when activated in the UI, the visual element should have a default value to be displayed correctly.

Take the "suggestions" for this (see below).

> Should there be defaults for deactivated values like currently defined in **/etc/tlp.conf** ?

Values of disabled parameters in tlp.conf having no intrinsic defaults are "suggestions". These may be the defaults for TLPUI when a parameter is enabled.

What a mess ... ;)

**Comment by d4nj1** [comment]
Hi @linrunner,
TLPUI currently supports TLP 0.8, 0.9, 1.0, 1.1 and 1.2. Here is my last questions:

- From which TLP version do the above mentioned config changes apply? Is the config behaviour supported by 0.8 upwards, or only by newer versions?

Kind regards

**Comment by linrunner** [comment]
I consider anything < 1.1 unsupported. But the queries for empty parameter values are also already available in 0.8.

**Comment by d4nj1** [comment]
@joakim-tjernlund @padok please check out newest master an test against your TLP 1.3 installation.

Feedback is appreciated

**Comment by oberon-manjaro** [comment]
Just tested on Manjaro and working fine. Thank you! :+1:

**Comment by yochananmarqos** [comment]
It's working well for me on Manjaro as well. Thankee sai!

**Comment by NICHOLAS85** [comment]
`CPU_ENERGY_PERF_POLICY_ON_BAT` seems to equal `power` in the UI although the value is `balance_power` in my `/etc/tlp.d/` drop-in file. Everything in `/etc/tlp.conf` is commented out (To use the intrinsic defaults). `/run/tlp/run.conf` reflects my drop-in settings aswell. I don't see any inconsistencies with my other settings added via drop-in, just this one.

**Comment by d4nj1** [comment]
Hi @NICHOLAS85,
I experienced the same behaviour. It was a selection bug in select box of the UI widget.
Should be fixed now.

**Comment by NICHOLAS85** [comment]
Latest commits have fixed the issue

**Comment by d4nj1** [comment]
As there have been no complains about the version upgrade for a week I am closing the issue.
