### ISSUE TITLE
set permanent hdd spin down via TLP-UI so the disk won't spin up/wake up by itself until command will be used

### ISSUE THREAD

**Issue by pgrycz** [d4nj1/TLPUI#63]
Is this option possible using TLP configuration? I had no problems with using hdparm app in Manjaro KDE linux to spin down hdd as I have whole system on ssd disk and hdd is used only as additional storage, no anything there is which system would treat as dependency to be run....so the command was used once and all worked and when I wanted to use this hdd disk it automatically spun up when disk icon was clicked...anyway since a week or two disk started to spin up same way like under Windows 10 which means something constantly wakes up this disk but I can't find what as I did no any changes in system only updates and new kernels (now kernel 5.5.2-1 version)

**Comment by d4nj1** [comment]
Hi,
sorry but this project is just providing the UI to change TLP configuration easily. If your think disk spindown misbehaviour has something to do with TLP please raise your issue request at https://github.com/linrunner/TLP.

Kind regards

**Comment by d4nj1** [comment]
Hi @pgrycz ,
I searched a bit on Google and maybe found a way how you can track down the process that is waking up your disk. There was a user with a similar setup as you and more or less the same behaviour:

https://bugs.launchpad.net/ubuntu/+source/udisks/+bug/638765

He set

`auditctl -w /dev/sdX -p rwa`

and discovered the wakeup process after disk spinup with

`ausearch -i`

Please keep in mind that I have not used **auditctl** myself. If you need any further information I kindly ask you to do an extened research yourself.

**Comment by pgrycz** [comment]
Thanks for response, yes, in the meantime I found probable issue cause using this `auditctl -w /dev/sdX -p rwa`, the `udisksd` service making smart polling for devices like DVD-ROM, etc but also probably for hard drives so the HDD wakes up periodically...there's something on arch wiki pages about using `udisks` and disable this smart polling, the thing is that it's deprecated and even I can't build this program from AUR/Arch source via update manager pamac...I instead have `udisks2` as current version of this program but these versions behaves differently, different commands, different features and it seems this `udisks2` can't disable smart polling so I have to build this `udisks` version in different way as I didn't found other way to disable this smart polling.
↓ below is what this `ausearch -i` prints out:
```
type=PROCTITLE msg=audit(27.02.2020 12:29:43.991:2270) : proctitle=/usr/lib/udisks2/udisksd 
type=PATH msg=audit(27.02.2020 12:29:43.991:2270) : item=0 name=/dev/sda inode=277 dev=00:06 mode=block,660 ouid=root ogid=disk rdev=08:00 nametype=NORMAL cap_fp=none cap_fi=none cap_fe=0 cap_fver=0 cap_frootid=0 
type=CWD msg=audit(27.02.2020 12:29:43.991:2270) : cwd=/ 
type=SYSCALL msg=audit(27.02.2020 12:29:43.991:2270) : arch=x86_64 syscall=openat success=yes exit=14 a0=0xffffff9c a1=0x55e83b0a9670 a2=O_RDONLY|O_NONBLOCK a3=0x0 items=1 ppid=1 pid=972 auid=unset uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=(none) ses=unset comm=pool-udisksd exe=/usr/lib/udisks2/udisksd subj==unconfined key=(null) 
----
type=USER_AUTH msg=audit(27.02.2020 12:29:53.844:2271) : pid=8369 uid=pawel auid=pawel ses=2 subj==unconfined msg='op=PAM:authentication grantors=pam_unix,pam_permit acct=pawel exe=/usr/bin/sudo hostname=? addr=? terminal=/dev/pts/0 res=success' 
----
type=USER_ACCT msg=audit(27.02.2020 12:29:53.844:2272) : pid=8369 uid=pawel auid=pawel ses=2 subj==unconfined msg='op=PAM:accounting grantors=pam_unix,pam_permit,pam_time acct=pawel exe=/usr/bin/sudo hostname=? addr=? terminal=/dev/pts/0 res=success' 
----
type=CRED_REFR msg=audit(27.02.2020 12:29:53.844:2273) : pid=8369 uid=root auid=pawel ses=2 subj==unconfined msg='op=PAM:setcred grantors=pam_unix,pam_permit acct=root exe=/usr/bin/sudo hostname=? addr=? terminal=/dev/pts/0 res=success' 
----
type=USER_START msg=audit(27.02.2020 12:29:53.847:2274) : pid=8369 uid=root auid=pawel ses=2 subj==unconfined msg='op=PAM:session_open grantors=pam_limits,pam_unix,pam_permit acct=root exe=/usr/bin/sudo hostname=? addr=? terminal=/dev/pts/0 res=success'
```
