### ISSUE TITLE
Support different configuration scheme in Clear Linux

### ISSUE THREAD

**Issue by jack23247** [d4nj1/TLPUI#64]
Clear Linux stores TLP's configuration file in a different folder, namely `/usr/share/defaults/tlp`. By trivially changing line 41 in _settings.py_ to `/usr/share/defaults/tlp` insetad of `/etc/default/tlp` I was able to make TLPUI work fine. 

Could distro detection be implemented and used to make this work automatically?

**Comment by SuperSandro2000** [comment]
I think it should rather check both paths regardless of OS or allow the configuration of the path.

**Comment by d4nj1** [comment]
Hi,
I would also like to solve this programatically. @linrunner could you tell us if TLP can return the path for user configuration file? I think until version 1.2 it was available via `tlp-stat -c`.

If this is not possible we could introduce an TLP_USER_CONFIG environment variable and use it when defined. Or TLPUI could also accept an optional argument to set the user configuration file.

**Comment by d4nj1** [comment]
Hi,
I went through the Clearlinux [tlp.spec](https://github.com/clearlinux-pkgs/TLP/blob/master/TLP.spec) and discovered that **TLP_CONF=/usr/share/defaults/tlp** is set.

Clearlinux describes **/usr/share/defaults** as a location to store [application defaults](https://docs.01.org/clearlinux/latest/guides/clear/stateless.html#software-configuration):
> Clear Linux OS distributed software packages may be directly modified to include default configuration values or default configuration files may be provided by Clear Linux OS under /usr/share/defaults. These files can be referenced as templates for customization.


So for me it means that the Clearlinux package should be fixed to adopt the config path that TLP uses in general. TLP versions prior 1.3 should use **/etc/default/tlp** and newer ones **/etc/tlp.conf**

For details please have a look at the [official TLP documentation](https://linrunner.de/en/tlp/docs/tlp-configuration.html):

Kind regards

**Comment by linrunner** [comment]
> So for me it means that the Clearlinux package should be fixed to adopt the config path that TLP uses in general. TLP versions prior 1.3 should use **/etc/default/tlp** and newer ones **/etc/tlp.conf**

+1 

As TLP's author I also strongly suggest to fix the Clear Linux TLP package. Storing user settings in **/usr/share** is contrary to FHS and users reading **/etc/tlp.conf** in my official docs will become unnecessarily confused.

**Comment by linrunner** [comment]
@d4nj1 : to answer your initial question to me: in principal tlp-stat -c does show PARAMETER="value"  Lnnn: <file>. But the native tlp.conf has all parameters commented, so /etc/tlp.conf will not appear in the outputin that situation.

**Comment by jack23247** [comment]
First of all, thanks to everyone for looking into this.
I'll do some tests in the following days, I think the confusion is because CL's TLP bundle is still on 1.2.2, and the packager got confused by the old config scheme.

**Comment by d4nj1** [comment]
Closing for now as there is no fix for TLPUI.
