### ISSUE TITLE
UI unreadable with dark Plasma style

### ISSUE THREAD

**Issue by defdef1** [d4nj1/TLPUI#65]
I recently changed my Plasma-design to Aritim-Dark and now TLPUI looks like this.
![Screenshot_20200417_133813](https://user-images.githubusercontent.com/45716812/79565736-94121080-80b1-11ea-9076-7d182c5ba706.png)

I don't experience this in any other application I use. Is it possible to fix this somehow without changing the global style?

**Comment by d4nj1** [comment]
Hi,
it could be due to the fast that I define `background-color: @theme_bg_color;` for the Gtk.Notebook that displays the categories and config items.
Could you please check if removing these lines in https://github.com/d4nj1/TLPUI/blob/master/tlpui/styles.css fix the issue for you?

Kind regards

**Comment by defdef1** [comment]
Many thanks, it worked like a charm! :)

**Comment by d4nj1** [comment]
Thanks for the feedback.
Will check on how to fix this. I might just remove the css override for now. Try to solve this in the near future.

**Comment by d4nj1** [comment]
Hi @defdef1,
should be fixed now. If possible please check out latest master and test if working.

Thanks in advance

**Comment by defdef1** [comment]
Which packages exactly do I need to for the cloned version (Arch)? When trying to run it I get:

`$ python3 -m tlpui
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/user/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/tlpui/TLPUI/tlpui/__main__.py", line 3, in <module>
    gi.require_version('Gtk', '3.0')
  File "/home/user/anaconda3/lib/python3.7/site-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available`

Looks like there's something missing, I have python-gobject and gtk3 installed though.

**Comment by d4nj1** [comment]
Ok, seems like some Gtk libraries are missing.
Maybe you could just replace your style.css with the content from https://github.com/d4nj1/TLPUI/blob/master/tlpui/styles.css to test it out.

**Comment by d4nj1** [comment]
Hi @defdef1,
could you check if **python3-gi** and **gir1.2-gtk-3.0** is installed?

**Comment by defdef1** [comment]
Hi,
as far as I know gtk3 is the equivalent to gir1.2-gtk-3.0 in Arch and there's also no package named python3-gi, maybe python-gobject is the equivalent here. python-gobject and tlp are the only requirements when I install tlpui via repositories.

I replaced my styles.css with yours and now it looks like this:
![Screenshot_20200426_112219](https://user-images.githubusercontent.com/45716812/80303394-577c9e00-87b0-11ea-8ad3-2535662aa5c1.png)

When I replace unfocsed with focused in lines 11 and 15 everything seems to be ok:
![Screenshot_20200426_112539](https://user-images.githubusercontent.com/45716812/80303478-d40f7c80-87b0-11ea-98dc-ae85813748bd.png)

**Comment by d4nj1** [comment]
Hi @defdef1,
I changed back to **bg_color**, but also applied **fg_color** so it should work as expected now. Would be very nice if you could check and try the latest css version https://github.com/d4nj1/TLPUI/blob/master/tlpui/styles.css and report back.

**Comment by defdef1** [comment]
Looks good now :+1: 
![Screenshot_20200429_150122](https://user-images.githubusercontent.com/45716812/80598911-548ce200-8a2a-11ea-86ed-4247e71adf4f.png)

**Comment by d4nj1** [comment]
Thanks for the feedback. If you experience any additional UI glitches, please do not hesitate to open another issue request.
