### ISSUE TITLE
CPU_SCALING_FREQ values suffix

### ISSUE THREAD

**Issue by mushonnip** [d4nj1/TLPUI#67]
It's a bit confusing when certain value doesn't have value suffix (either kHz, MHz, GHz, or etc.)

**Comment by d4nj1** [comment]
Hi,
I think that will be a bit tricky. If you read kernel documentation a bit you will see that stepping is dependent on the selected cpu scaling governor.

https://www.kernel.org/doc/html/latest/admin-guide/pm/cpufreq.html

What I could add to the UI would be the default **min** and **max** values that can be read from the system configuration information like this for example (policy0 for the first CPU):

`cat /sys/devices/system/cpu/cpufreq/policy0/cpuinfo_min_freq`
and
`cat /sys/devices/system/cpu/cpufreq/policy0/cpuinfo_max_freq`

These values are described to be in **khz** format. This seems to apply at least from kernel 4.12 and onwards (kernel.org had no older kernel documentation regarding this).

@mushonnip 
So to conclude. If only the suffix matters for you it should be safe to just add **khz** to the UI. Would that be ok?

**Comment by d4nj1** [comment]
Added as requested.
