### ISSUE TITLE
New release - tlpui-1.3

### ISSUE THREAD

**Issue by Srikanth-M-02** [d4nj1/TLPUI#68]
Can you consider doing a new release in releases called tlp-1.3

**Comment by d4nj1** [comment]
Hi,
can you tell me why you would like to have a new "release"?

**Comment by Srikanth-M-02** [comment]
I thought that given that you have the practice of using releases,it would be better if the newest release works with tlp

**Comment by d4nj1** [comment]
I added this 1.2 "release" tag when I was updating TLPUI to support tlp 1.3 which had some internal changes how configuration is handled. During that time I was unsure if TLPUI would stay downwards compatible. As I found a way to support all version from 0.8-1.3 this tag is obsolete. I just removed it.

Thanks and kind regards

**Comment by SuperSandro2000** [comment]
It would make it a lot easier for package maintainers if you would take release versions like 1.2 or 1.3.

**Comment by d4nj1** [comment]
@SuperSandro2000 That's a fair reason. Will evaluate where and when to set tags. Try to add some soon.
