### ISSUE TITLE
It shows settings for Radeon even though I have a Nvidia GPU

### ISSUE THREAD

**Issue by QazCetelic** [d4nj1/TLPUI#70]
Or is it just a generic name for all GPU's?

**Comment by kortewegdevries** [comment]
> Or is it just a generic name for all GPU's?

[These?](https://imgur.com/3vjGGfG)

**Comment by d4nj1** [comment]
Hi @QazCetelic,
it's more like configuration that you "can" apply if you have Radeon GPU with the correct kernel module loaded. For more specific details see https://linrunner.de/tlp/settings/graphics.html

TLPUI does not check for available graphics card at the moment and just provides a UI for all available config items that exist.

**Comment by d4nj1** [comment]
If you have further questions please reopen the issue.
