### ISSUE TITLE
How do I disable my desktop PC from waking up from hibernation and sleep?

### ISSUE THREAD

**Issue by Joe23232** [d4nj1/TLPUI#73]
Whenever I put my desktop PC to either sleep or hibernation, if I move the mouse it will wake the PC up. I believe I have to suspend my USB devices or something but it is enabled but it still doesn't turn it off, is there some setting to disable wake from hibernation or sleep from my mouse and keyboard?

**Comment by d4nj1** [comment]
Hi,
I only provide the UI for [TLP](https://github.com/linrunner/TLP) so I kindly ask you to move your question there or elsewhere as there may be lots of reasons why hibernate is failing. This might even not be related to your USB mouse or TLP at all.

Kind regards

**Comment by Joe23232** [comment]
Sure man.
