### ISSUE TITLE
Command not working

### ISSUE THREAD

**Issue by naiemofficial** [d4nj1/TLPUI#77]
When I run this command `$ sudo add-apt-repository -y ppa:linuxuprising/apps`
I'm getting the following error 
```
pg: keybox '/tmp/tmpi5kkkb_h/pubring.gpg' created
gpg: /tmp/tmpi5kkkb_h/trustdb.gpg: trustdb created
gpg: key EA8CACC073C3DB2A: public key "Launchpad PPA for Linux Uprising" imported
gpg: Total number processed: 1
gpg:               imported: 1
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
gpg: no valid OpenPGP data found.
```
Reference: [https://github.com/d4nj1/TLPUI/wiki/Install-instructions#python-3](https://github.com/d4nj1/TLPUI/wiki/Install-instructions#python-3)

**Comment by d4nj1** [comment]
Hi @naiemofficial,
that's the offial way for this ppa to be added, see https://launchpad.net/~linuxuprising/+archive/ubuntu/apps
Could it be that you are not on Ubuntu but on Debian or another Debain based distribution? If this is the case I should maybe adjust the documentation to describe Ubuntu exclusively. It seems like their PPA is for Ubuntu systems only.

**Comment by d4nj1** [comment]
I updated the documentation in the wiki so it only mentions the PPA for Ubuntu usage.
