### ISSUE TITLE
application icon not displayed in xfce4

### ISSUE THREAD

**Issue by squalou** [d4nj1/TLPUI#78]
Hi,

This is a minor annoyance, yet why not report it :)

I installed on Arch from AUR package, and everything works fine.
When searching for the .desktop launcher using classical menu, it's fine, preferences-system-power-management icon is displayed.
Same thing if I use Synapse as app launcher.

Only issue I have is once it's launched,
- top border window has deffault icon instead
- panel window shortcut has also default icon

I'm running latest xfce4 desktop with nothing fancy, any additional info available if I can help anyhow.

Here are some screenshots :

Here, the icon well displayed inside menu

![image](https://user-images.githubusercontent.com/4623644/97886192-945dba80-1d28-11eb-8490-d7c834f8fd75.png)

But there : onece launched

![image](https://user-images.githubusercontent.com/4623644/97886417-df77cd80-1d28-11eb-8e4e-83879403359f.png)

thax for reading, and for the work : this UI is awesome

**Comment by squalou** [comment]
As it happens I found an easy fix, in __main__.py line 31 I added this :

```python
window.set_icon_name('preferences-system-power-management')
```

here s the git diff output

```bash
~/srcAlt/TLPUI[master|✚1]$ git diff
diff --git a/tlpui/__main__.py b/tlpui/__main__.py
index b94330d..56b024a 100755
--- a/tlpui/__main__.py
+++ b/tlpui/__main__.py
@@ -28,6 +28,7 @@ def main() -> None:
     # init application window
     window = Gtk.Window()
     window.set_title('Tlp-UI')
+    window.set_icon_name('preferences-system-power-management')
     window.set_default_size(settings.windowxsize, settings.windowysize)
     window.add(create_main_box(window))
     window.connect('check-resize', store_window_size)
```

**Comment by squalou** [comment]
Note : all this being said ... could be that the .desktop file and all comes from the Arch packaging, not your repo.

Maybe you'd prefer another icon name ?

Anyway, do as you please, it's really a minor thing.

**Comment by d4nj1** [comment]
Hi and thanks for the hint.
I just added a default icon with fallback. This might be changed once I find time and creativity to create a custom TLPUI icon. ;)
