### ISSUE TITLE
can't run on manjaro

### ISSUE THREAD

**Issue by KairuiLiu** [d4nj1/TLPUI#85]
I try to unzip and run setup.py shows that
```
    ~/Pu/program/TLPUI-tlpui-1.3.1-3     09:31:21   221.7.112.19   100%  
❯ python ./setup.py                         ⇣9.08 KiB/s ⇡0.3 KiB/s 10.124.184.15  
/usr/lib/python3.9/site-packages/setuptools/dist.py:452: UserWarning: Normalizing '1.3.1-3' to '1.3.1.post3'
  warnings.warn(tmpl.format(**locals()))
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied
```
then run tlpui.desktop shows can't find /usr/bin/tlpui

thanks!

**Comment by d4nj1** [comment]
Hi @KairuiLiu ,
there is currently no install process for setup.py other that for Debian basaed distributions. Maybe I will add some pip3 process to install the library in future. Nothing done yet.

To execute the UI with Python please follow these instructions: https://github.com/d4nj1/TLPUI/wiki/Install-instructions#python-3

**Comment by yochananmarqos** [comment]
@KairuiLiu `tlpui` is in the Manjaro community repo, you can install it via Add / Remove Software.
