### ISSUE TITLE
undefined symbol: cairo_font_options_get_variation

### ISSUE THREAD

**Issue by TsaiFish** [d4nj1/TLPUI#87]
I cannot open it, and the following is the error message.

(tlp-ui:14936): Gtk-WARNING **: 11:18:10.103: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../gtk/gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Papirus-Dark/16x16/actions/image-missing.svg: Unable to load image-loading module: /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /usr/lib/librsvg-2.so.2: undefined symbol: cairo_font_options_get_variations (gdk-pixbuf-error-quark, 5)
Bail out! Gtk:ERROR:../gtk/gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Papirus-Dark/16x16/actions/image-missing.svg: Unable to load image-loading module: /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /usr/lib/librsvg-2.so.2: undefined symbol: cairo_font_options_get_variations (gdk-pixbuf-error-quark, 5)
zsh: abort (core dumped)  tlpui

**Comment by d4nj1** [comment]
Hi,
I searched for this on the web and it may either be related to your icon theme, or to an error in Gtk itself which I somehow doubt.
So for a first test please choose another, or the default theme+icons and report back if the error still exists. If it exists please share some further information of your system like distribution+version, the desktop environment and selected themes+icons. Then it should be easier to reproduce.

Kind regards

**Comment by d4nj1** [comment]
Hi @TsaiFish,
did you solve the issue? If not, can you provide more information?

Thanks in advance

**Comment by d4nj1** [comment]
I think there is nothing to do for me. Please reopen with required information provided if still interested.

Kind regards
