### ISSUE TITLE
Flatpak builder doen't work

### ISSUE THREAD

**Issue by KarkanAlzwayed** [d4nj1/TLPUI#95]
I don't know if this is still being worked on, or whether the title is the best description for the issue, but I am going to throw it here anyway in hope that it helps in some way.
when running 
`flatpak-builder --force-clean --user --install build-dir com.github.d4nj1.tlpui.json` from [here](https://github.com/d4nj1/TLPUI/tree/master/flatpak)
I got this:
```
bash: flatpak-builder: command not found...
Install package 'flatpak-builder' to provide command 'flatpak-builder'? [N/y] y


 * Waiting in queue... 
The following packages have to be installed:
 ccache-4.2-1.fc34.x86_64	C/C++ compiler cache
 flatpak-builder-1.0.12-3.fc34.x86_64	Tool to build flatpaks from source
Proceed with changes? [N/y] y


 * Waiting in queue... 
 * Waiting for authentication... 
 * Waiting in queue... 
 * Downloading packages... 
 * Requesting data... 
 * Testing changes... 
 * Installing packages... 
Can't load 'com.github.d4nj1.tlpui.json': Failed to open file “/home/kalzi/com.github.d4nj1.tlpui.json”: No such file or directory

```
Then continued trying and this is also what I got:

```
[kalzi@fedora ~]$ flatpak run com.github.d4nj1.tlpui
error: app/com.github.d4nj1.tlpui/x86_64/master not installed
[kalzi@fedora ~]$ flatpak run com.github.d4nj1.tlpui
error: app/com.github.d4nj1.tlpui/x86_64/master not installed
[kalzi@fedora ~]$ flatpak-builder --force-clean --user --install build-dir com.github.d4nj1.tlpui.json
Can't load 'com.github.d4nj1.tlpui.json': Failed to open file “/home/kalzi/com.github.d4nj1.tlpui.json”: No such file or directory
[kalzi@fedora ~]$ sudo flatpak-builder --force-clean --user --install build-dir com.github.d4nj1.tlpui.json
[sudo] password for kalzi: 
Can't load 'com.github.d4nj1.tlpui.json': Failed to open file “/home/kalzi/com.github.d4nj1.tlpui.json”: No such file or directory
[kalzi@fedora ~]$ flatpak-builder --force-clean --user --install build-dir com.github.d4nj1.tlpui.json
Can't load 'com.github.d4nj1.tlpui.json': Failed to open file “/home/kalzi/com.github.d4nj1.tlpui.json”: No such file or directory




```
I have resorted to the "git clone" and "python3 -m tlpui for now.
Hope this helps

**Comment by d4nj1** [comment]
Hi,
you have to execute the `flatpak-builder` command from within the **flatpak** folder.
I just updated the documentation, see [here](https://github.com/d4nj1/TLPUI/tree/master/flatpak).
It now also recommends to install runtime and SDK as needed for the build.

Would be great if you could test and report back.

Thanks in advance

**Comment by KarkanAlzwayed** [comment]
Ok, that did work, but it is basically doing the same thing but replacing the command `python3 -m tlpui` with `flatpak run com.github.d4nj1.tlpui`. Or am I mistaken?
I got happy for a second, I though I was getting an actual app that I can find in my app drawer and add it to my dock.

**Comment by d4nj1** [comment]
Hi @KarkanAlzwayed 
I just uploaded the new TLPUI icon and added some desktop integration for Flatpak.
Could you please update to latest master branch and rerun the Flatpak build?

TLP UI application starter should then appear in "settings". Please report back if possible.

Thanks in advance

**Comment by KarkanAlzwayed** [comment]
There it is 😄
Thanks a lot. A question, though. Do I need to `git pull `every time I want the latest update, or will it show in my gnome software when there is an update available since I have already added the flathub repo? (I have flathub installed in the gnome software)
![Screenshot from 2021-07-14 22-45-37](https://user-images.githubusercontent.com/49320606/125719970-e6bdb6f7-f485-4fe3-b2c8-15395643e4cc.png)

**Comment by d4nj1** [comment]
Hi,
great that it serves your needs now. Sadly you will have to pull and rebuild on every change to master until I am able to release it on flathub.org . Theoretically it should be updateable once it gets released. I don't know if there is any metadata added to flathub.org packages that would prevent updating from a custom build. We will find out ;)
