### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by Hayao0819** [d4nj1/TLPUI#97]
I'm an Arch Linux user and a TLPUI user.  
I have created and posted tlpui PKGBUILD in AUR,  
Add a guide for Arch Linux users to the README.  

https://aur.archlinux.org/packages/tlpui/

**Comment by yochananmarqos** [comment]
[`tlpui-git` ](https://aur.archlinux.org/packages/tlpui-git)has been aroud since 2018, FYI. 😉

**Comment by d4nj1** [comment]
@yochananmarqos ,
I know that this was existing before. I thought that the **tlpui** package would be the successor/final package of the **tlpui-git** one. Then which one is the recommended to be used? I can probably add both to the documentation, but I would also like to not confuse users. So please enlighten my mind so I can either add some more description for both packages, or remove the link to any AUR package completely.

Thanks in advance

**Comment by yochananmarqos** [comment]
@d4nj1: `tlpui` is the stable release version while `tlpui-git` is the VCS development package pulling directly from master.

**Comment by d4nj1** [comment]
@yochananmarqos ,
that's a fair reason to add both. I just updated the documentation for Arch Linux, see https://github.com/d4nj1/TLPUI/wiki/Install-instructions#arch-linux
Sorry for not adding the package to the wiki beforehand.
