### ISSUE TITLE
Add support for ideapad batteries

### ISSUE THREAD

**Issue by stavros-k** [d4nj1/TLPUI#99]
With TLP1.4 (beta for now) there is support for ideapad laptop batteries, in which it's conservation mode is a toggle (on or off), which is activated via TLP by setting `STOP_CHARGE_THRESH_BAT0=1`.  Currently in TLPUI in the `Thinkpad Battery` section the minimum value of `STOP_CHARGE_THRESH_BAT0` is `5`
It would be nice if there was a section for all ideapad supported features, you might want to hold it tho until there is an actual stable release. 

Thanks

**Comment by d4nj1** [comment]
Hi,
thanks for the input. I just updated TLPUI to match the TLP 1.4 final config so it should be working as expected now.
